CREATE TABLE IF NOT EXISTS books (
    id_llibre BIGINT AUTO_INCREMENT PRIMARY KEY,
    titol VARCHAR(255) NOT NULL,
    autor VARCHAR(255) NOT NULL,
    isbn VARCHAR(255) NOT NULL UNIQUE,
    data_publicacio DATE NOT NULL,
    preu DECIMAL(10,2) NOT NULL,
    editorial VARCHAR(255) NOT NULL
);